from loome import ARINC429, GPIO, RS232, Component, Connector, GarminEthernet, Pin


class GTN650Xi(Component):
    """GPS/NAV/COM (GTN 650Xi)"""

    system = "GPS"

    class P1001(Connector):
        """Main Connector – Main Board"""

        main_obs_rotor_h_gnd = Pin(1, "Main OBS Rotor H (GND)")
        main_obs_rotor_c = Pin(2, "Main OBS Rotor C")
        time_mark_out_a = Pin(3, "Time Mark Out A")
        audio_out_hi = Pin(4, "Audio Out Hi")

        rs232_4 = RS232(5, 24, 44, "RS-232 4")
        rs232_3 = RS232(6, 25, 44, "RS-232 3")
        rs232_2 = RS232(7, 26, 45, "RS-232 2")
        rs232_1 = RS232(8, 27, 46, "RS-232 1")

        arinc_429_out_2 = ARINC429(9, 28, "out", name="ARINC 429 Out 2")
        arinc_429_out_1 = ARINC429(10, 29, "out", name="ARINC 429 Out 1")
        main_to_out = Pin(11, "Main +TO Out")
        main_vertical_up_out = Pin(12, "Main Vertical +UP Out")
        main_lateral_superflag_out = Pin(13, "Main Lateral Superflag Out")
        obs_annunciate = Pin(14, "OBS Annunciate*")
        gps_annunciate = Pin(15, "GPS Annunciate*")
        obs_mode_select = Pin(16, "OBS Mode Select*")
        lighting_bus_1_lo = Pin(17, "Lighting Bus 1 Lo")
        lighting_bus_1_hi = Pin(18, "Lighting Bus 1 Hi")
        aircraft_power_a = Pin(19, "Aircraft Power A")
        aircraft_power_b = Pin(20, "Aircraft Power B")
        main_obs_stator_d = Pin(21, "Main OBS Stator D")
        time_mark_out_b = Pin(22, "Time Mark Out B")
        audio_out_lo = Pin(23, "Audio Out Lo")

        # pins 24-27: RS-232 RX (part of rs232_1–4 above)
        # pins 44-46: RS-232 GND (part of rs232_1–4 above)

        main_from_out = Pin(30, "Main +FROM Out")
        main_vertical_down_out = Pin(31, "Main Vertical +DOWN Out")
        main_vertical_superflag_out = Pin(32, "Main Vertical Superflag Out")
        waypoint_annunciate = Pin(33, "Waypoint Annunciate*")
        terminal_annunciate = Pin(34, "Terminal Annunciate*")
        taws_audio_active_out = Pin(35, "TAWS Audio Active Out*")
        audio_inhibit_in = Pin(36, "Audio Inhibit In*")
        taws_inhibit_in = Pin(37, "TAWS Inhibit In*")
        air_ground = Pin(38, "Air/Ground*")
        cdi_source_select = Pin(39, "CDI Source Select*")
        main_obs_stator_e_gnd = Pin(40, "Main OBS Stator E (GND)")
        main_obs_stator_f = Pin(41, "Main OBS Stator F")
        lighting_bus_2_lo = Pin(42, "Lighting Bus 2 Lo")
        fan = GPIO(59, 58, 43, name="Fan")

        arinc_429_in_2 = ARINC429(47, 66, "in", name="ARINC 429 In 2")
        arinc_429_in_1 = ARINC429(48, 67, "in", name="ARINC 429 In 1")
        main_lateral_left_out = Pin(49, "Main Lateral +LEFT Out")
        main_lateral_pos_flag_out = Pin(50, "Main Lateral +FLAG Out")
        main_vertical_pos_flag_out = Pin(51, "Main Vertical +FLAG Out")
        vor_loc_annunciate = Pin(52, "VOR/LOC Annunciate*")
        loi_annunciate = Pin(53, "LOI Annunciate*")
        message_annunciate = Pin(54, "Message Annunciate*")
        approach_annunciate = Pin(55, "Approach Annunciate*")
        ils_gps_approach = Pin(56, "ILS/GPS Approach*")
        taws_inhibit_annunciate = Pin(57, "TAWS Inhibit Annunciate*")
        main_obs_stator_g_gnd = Pin(60, "Main OBS Stator G (GND)")
        lighting_bus_2_hi = Pin(61, "Lighting Bus 2 Hi")
        config_module_data = Pin(62, "Config Module Data")
        config_module_clock = Pin(63, "Config Module Clock")
        config_module_gnd = Pin(64, "Config Module GND")
        config_module_power = Pin(65, "Config Module Power")
        main_lateral_right_out = Pin(68, "Main Lateral +RIGHT Out")
        main_lateral_neg_flag_out = Pin(69, "Main Lateral -FLAG Out")
        main_vertical_neg_flag_out = Pin(70, "Main Vertical -FLAG Out")
        terrain_warning_annunciate = Pin(71, "Terrain Warning Annunciate*")
        terrain_not_available_annunciate = Pin(72, "Terrain Not Available Annunciate*")
        terrain_caution_annunciate = Pin(73, "Terrain Caution Annunciate*")
        gps_select = Pin(74, "GPS Select*")
        traffic_test = Pin(75, "Traffic Test*")
        traffic_standby = Pin(76, "Traffic Standby*")
        aircraft_gnd_a = Pin(77, "Aircraft GND A")
        aircraft_gnd_b = Pin(78, "Aircraft GND B")

    class P1002(Connector):
        """Main Board Connector"""

        demo_mode_select = Pin(1, "Demo Mode Select*")
        suspend_annunciate = Pin(3, "Suspend Annunciate*")
        ethernet_out_4 = GarminEthernet(4, 5, "out", name="Ethernet Out 4")
        ethernet_in_1 = GarminEthernet(6, 7, "in", name="Ethernet In 1")
        ethernet_out_1 = GarminEthernet(8, 9, "out", name="Ethernet Out 1")
        spare_input = Pin(10, "Spare Input*")
        gsr_status_in = Pin(11, "GSR Status In*")
        gsr_remote_power_out = Pin(12, "GSR Remote Power Out*")
        ethernet_in_4 = GarminEthernet(13, 14, "in", name="Ethernet In 4")
        ethernet_in_2 = GarminEthernet(15, 16, "in", name="Ethernet In 2")
        ethernet_out_2 = GarminEthernet(17, 18, "out", name="Ethernet Out 2")
        ethernet_in_3 = GarminEthernet(23, 24, "in", name="Ethernet In 3")
        ethernet_out_3 = GarminEthernet(25, 26, "out", name="Ethernet Out 3")

    class P1003(Connector):
        """COM Connector"""

        com_mic_1_audio_in_hi = Pin(5, "COM Mic 1 Audio In Hi")
        com_audio_hi = Pin(7, "500Ω COM Audio Hi")
        transmit_interlock = Pin(9, "Transmit Interlock*")
        com_mic_1_key = Pin(11, "COM Mic 1 Key*")
        com_audio_lo = Pin(18, "500Ω COM Audio Lo")
        mic_audio_in_lo = Pin(20, "Mic Audio In Lo")
        com_remote_transfer = Pin(27, "COM Remote Transfer*")
        com_remote_tune_up = Pin(28, "COM Remote Tune Up*")
        com_remote_tune_down = Pin(29, "COM Remote Tune Down*")
        aircraft_power_a = Pin(30, "Aircraft Power A")
        aircraft_gnd_a = Pin(37, "Aircraft GND A")
        aircraft_gnd_b = Pin(38, "Aircraft GND B")
        aircraft_gnd_c = Pin(40, "Aircraft GND C")
        aircraft_power_b = Pin(43, "Aircraft Power B")
        aircraft_power_c = Pin(44, "Aircraft Power C")

    class P1004(Connector):
        """NAV Connector"""

        vor_loc_to = Pin(1, "VOR/LOC +TO")
        vor_loc_from = Pin(2, "VOR/LOC +FROM")
        vor_loc_pos_flag = Pin(3, "VOR/LOC +FLAG")
        vor_loc_neg_flag = Pin(4, "VOR/LOC -FLAG")
        vor_loc_left = Pin(5, "VOR/LOC +LEFT")
        vor_loc_right = Pin(6, "VOR/LOC +RIGHT")
        vor_loc_composite_out = Pin(8, "VOR/LOC Composite Out")
        vor_obs_rotor_c = Pin(9, "VOR OBS Rotor C")
        vor_obs_rotor_h_gnd = Pin(10, "VOR OBS Rotor H (GND)")
        vor_obs_stator_e_gnd = Pin(11, "VOR OBS Stator E (GND)")
        vor_obs_stator_f = Pin(12, "VOR OBS Stator F")
        vor_obs_stator_d = Pin(13, "VOR OBS Stator D")
        vor_obs_stator_g_gnd = Pin(14, "VOR OBS Stator G (GND)")
        vor_loc_superflag = Pin(15, "VOR/LOC Superflag")
        vor_loc_audio_out_hi = Pin(16, "500Ω VOR/LOC Audio Out Hi")
        vor_loc_audio_out_lo = Pin(17, "500Ω VOR/LOC Audio Out Lo")
        serial_dme_clock = Pin(18, "Serial DME Clock")
        serial_dme_data = Pin(19, "Serial DME Data")
        serial_dme_rnav_ch_req = Pin(20, "Serial DME RNAV/CH Req")
        serial_dme_rnav_mode = Pin(21, "Serial DME RNAV Mode")
        aircraft_gnd_a = Pin(22, "Aircraft GND A")
        vor_ils_arinc_429_out = ARINC429(24, 23, "out", name="VOR/ILS ARINC 429 Out")
        vor_obi_clock = Pin(25, "VOR OBI Clock")
        vor_obi_sync = Pin(26, "VOR OBI Sync")
        vor_obi_data = Pin(27, "VOR OBI Data")
        vloc_remote_transfer = Pin(28, "VLOC Remote Transfer")
        ils_energize = Pin(29, "ILS Energize")
        glideslope_pos_flag = Pin(32, "Glideslope +FLAG")
        par_dme_1mhz_d = Pin(33, "PAR DME 1MHz-D / Serial DME On")
        glideslope_up = Pin(34, "Glideslope +UP")
        vor_ils_arinc_429_in = ARINC429(36, 35, "in", name="VOR/ILS ARINC 429 In")
        par_dme_100khz_a = Pin(37, "PAR DME 100kHz-A / Serial DME Hold*")
        glideslope_superflag = Pin(38, "Glideslope Superflag")
        par_dme_100khz_b = Pin(39, "PAR DME 100kHz-B")
        par_dme_100khz_c = Pin(40, "PAR DME 100kHz-C")
        dme_common = Pin(41, "DME Common")
        par_dme_100khz_d = Pin(42, "PAR DME 100kHz-D")
        par_dme_50khz = Pin(43, "PAR DME 50kHz")
        serial_dme_request = Pin(44, "Serial DME Request")
        par_dme_1mhz_a = Pin(45, "PAR DME 1MHz-A")
        par_dme_1mhz_b = Pin(46, "PAR DME 1MHz-B")
        par_dme_1mhz_c = Pin(47, "PAR DME 1MHz-C")
        aircraft_gnd_b = Pin(49, "Aircraft GND B")
        aircraft_power_a = Pin(51, "Aircraft Power A")
        aircraft_power_b = Pin(52, "Aircraft Power B")
        glideslope_neg_flag = Pin(53, "Glideslope -FLAG")
        par_dme_100khz_e = Pin(54, "PAR DME 100kHz-E")
        glideslope_down = Pin(55, "Glideslope +DOWN")
        par_dme_1mhz_e = Pin(56, "PAR DME 1MHz-E")
        aircraft_gnd_c = Pin(60, "Aircraft GND C")
        aircraft_gnd_d = Pin(61, "Aircraft GND D")
        aircraft_gnd_e = Pin(62, "Aircraft GND E")

    class P1005(Connector):
        """GTN 725Xi/750Xi Connector"""

        arinc_429_in_5 = ARINC429(26, 5, "in", name="ARINC 429 In 5")
        arinc_429_out_4 = ARINC429(27, 6, "out", name="ARINC 429 Out 4")
        arinc_429_out_3 = ARINC429(28, 7, "out", name="ARINC 429 Out 3")
        rs232_5 = RS232(8, 29, 49, "RS-232 5")
        rs232_6 = RS232(9, 30, 50, "RS-232 6")
        wx_radar_on = Pin(13, "WX Radar On*")
        synchro_y = Pin(14, "Synchro Y")
        synchro_ref_lo = Pin(15, "Synchro Ref Lo")
        arinc_429_in_3 = ARINC429(37, 16, "in", name="ARINC 429 In 3")
        arinc_429_in_4 = ARINC429(38, 17, "in", name="ARINC 429 In 4")
        arinc_453_708_in_1a = Pin(18, "ARINC 453/708 In 1A")
        arinc_453_708_term_1b = Pin(19, "ARINC 453/708 Term 1B")
        arinc_453_708_in_2a = Pin(20, "ARINC 453/708 In 2A")
        arinc_453_708_term_2b = Pin(21, "ARINC 453/708 Term 2B")
        synchro_valid_lo = Pin(33, "Synchro Valid Lo")
        spare_output = Pin(34, "Spare Output*")
        synchro_x = Pin(35, "Synchro X")
        synchro_ref_hi = Pin(36, "Synchro Ref Hi")
        arinc_453_708_term_1a = Pin(40, "ARINC 453/708 Term 1A")
        arinc_453_708_term_2a = Pin(42, "ARINC 453/708 Term 2A")
        spare_input = Pin(53, "Spare Input*")
        synchro_valid_hi = Pin(54, "Synchro Valid Hi")
        synchro_z = Pin(56, "Synchro Z")
        arinc_453_708_in_1b = Pin(60, "ARINC 453/708 In 1B")
        arinc_453_708_in_2b = Pin(62, "ARINC 453/708 In 2B")
